# Generated by Django 3.2.4 on 2021-08-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='seller-qrcode'),
        ),
    ]
