# Generated by Django 3.2.4 on 2021-08-09 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='seller-qrcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
