# Generated by Django 3.2.4 on 2021-08-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_sellerqrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerQrcode',
        ),
    ]
