# Generated by Django 3.2.4 on 2021-06-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation_variationvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationvalue',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
    ]
