# Generated by Django 3.2.4 on 2021-06-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_variationvalue_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
