# Generated by Django 3.2.4 on 2021-06-19 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20210618_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_cart', to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_order', to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='vendor_total',
            field=models.FloatField(default=0.0),
        ),
    ]
