# Generated by Django 3.2.4 on 2021-06-19 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20210619_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vendor',
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ManyToManyField(related_name='vendor_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
