# Generated by Django 3.2.4 on 2021-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210619_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('PayPal', 'PayPal'), ('SSLCommerz', 'SSLCommerz')], default='Cash On Delivery', max_length=30),
        ),
    ]
